don't abort in galaxy-backup-db.sh script when 'swift delete' fails

diff --git a/roles/slg.db-backup/templates/galaxy-backup-db.sh.j2 b/roles/slg.db-backup/templates/galaxy-backup-db.sh.j2
--- a/roles/slg.db-backup/templates/galaxy-backup-db.sh.j2
+++ b/roles/slg.db-backup/templates/galaxy-backup-db.sh.j2
@@ -127,17 +127,21 @@ swift --quiet upload --segment-size 2000000000 ${SWIFT_BACKUP_CONTAINER} ${backu
 
 {% endif %}
 
+# don't exit on swift errors
+set +e
 for f in $(<search_file.tmp)
     do
         echo $f
         {% if use_swift == true %}
         echo '  Deleting on swift: '$f >> $LOGFILE
-        #delete cloud copy
-        swift delete ${SWIFT_BACKUP_CONTAINER} $f
+        #delete cloud copy and log error if delete fails
+        swift delete ${SWIFT_BACKUP_CONTAINER} $f || '  swift delete failed for: '$f >> $LOGFILE
         {% endif %}
         #delete local copy
         rm $f
     done
+# restore exit on fail
+set -e
 
 rm search_file.tmp
 
