don't abort in galaxy-backup-db.sh script when 'swift delete' fails (#1345)
* don't abort in galaxy-backup-db.sh script when 'swift delete' fails

* fix typo in logging swift delete error

* add current swift options from aarnet-backup to galaxy-backup-db.sh template

* fix typo in galaxy-backup-db.sh template

* define db_server as the internal IP address of aarnet-db so that the postgres connection string has the correct IP address

* change backup time from 23 UTC = 9am AEST to 18 UTC = 4am AEST

diff --git a/roles/slg.db-backup/templates/galaxy-backup-db.sh.j2 b/roles/slg.db-backup/templates/galaxy-backup-db.sh.j2
--- a/roles/slg.db-backup/templates/galaxy-backup-db.sh.j2
+++ b/roles/slg.db-backup/templates/galaxy-backup-db.sh.j2
@@ -108,7 +108,7 @@ pg_dump \
 
 #delete anything that's too old!
 #put the filenames in a file so we can get rid of them from object store.
-if [ -f search_file.ymp ] ; then
+if [ -f search_file.tmp ] ; then
         rm search_file.tmp
 fi
 find -maxdepth 1 -name "*${BACKUP_TYPE}*" -mtime +$RETENTION_DAY_LOOKUP > search_file.tmp
@@ -123,21 +123,25 @@ set +o nounset
 source ${VENV_LOCATION}/bin/activate
 set -o nounset
 
-swift --quiet upload --segment-size 2000000000 ${SWIFT_BACKUP_CONTAINER} ${backup_filename}
+swift --quiet --retries 5 --timeout 120 upload --segment-size 2000000000 --segment-threads 1 ${SWIFT_BACKUP_CONTAINER} ${backup_filename}
 
 {% endif %}
 
+# don't exit on swift errors
+set +e
 for f in $(<search_file.tmp)
     do
         echo $f
         {% if use_swift == true %}
         echo '  Deleting on swift: '$f >> $LOGFILE
-        #delete cloud copy
-        swift delete ${SWIFT_BACKUP_CONTAINER} $f
+        #delete cloud copy and log error if delete fails
+        swift --retries 5 --timeout 120 delete --object-threads 1 ${SWIFT_BACKUP_CONTAINER} $f || echo '  swift delete failed for: '$f >> $LOGFILE
         {% endif %}
         #delete local copy
         rm $f
     done
+# restore exit on fail
+set -e
 
 rm search_file.tmp
 
